title: Rofdservices
author: rofdservices
email: wip@wip.com
description: >-
  ROFD Services is een klusbedrijf sinds 2010 actief op de Nederlandse markt. Met vestingen in Amstelveen , leveren wij maatwerk in de Regio Amsterdam. Renovatie verbouwen en onderhoud buiten en binnenshuis .
  Ons enthousiaste en professionele team heeft veel oog voor kwaliteit en details. Onze prijzen zijn markt conform, en onze offertes maken we allen na persoonlijk onderhoud met de opdrachtgever.
  Gedurende de laatste jaren hebben wij ons gespecialiseerd in binnen en buiten schilderwerk, timmerwerk, stukwerk, tegelzetten toilet renovatie badkamer verbouwen, badkamer bouwen en installatiewerk. Ook vloeren, afwerkvloeren en laminaat kunnen wij voor u verzorgen.
  Bel ons: 0652729191 of stuur een bericht om contact te maken voor een kosteloos offerte.
keywords: rofd, services, renovatie, badkamer, keuken, badkamer verbouw amsterdam, klusbedrijf amstelveen
deploy:
  source: git@github.com:rofdservices/rofdservices.github.io.git
  branch: live
  dir: _production

url: "https://rofdservices.nl"

plugins:
  - jekyll-menus

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - _deploy
