title: Rofdservices
author: rofdservices
email: wip@wip.com
description: >-
  ROFD Services is een klusbedrijf sinds 2010 actief op de Nederlandse markt.
  Met vestingen in Amstelveen, leveren wij maatwerk in de Regio Amsterdam.
  Renovatie verbouwen en onderhoud buiten en binnenshuis.
keywords: rofd, services, renovatie, badkamer, keuken

# baseurl: "/ubuild-jekyll" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-menus
